apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world-app
  template:
    metadata:
      labels:
        app: hello-world-app
    spec:
      dnsPolicy: Default  # Add this line to set the DNS policy
      containers:
        - name: hello-world-container
          image: pankhuri79/pankh79
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
